add_library(ARCORE::ARCORE SHARED IMPORTED)

set(ARCORE_FOUND 1 CACHE INTERNAL "ARCORE found" FORCE)
set(ARCORE_LIBRARIES "${ARCORE_LIBPATH}/${ANDROID_ABI}/libarcore_sdk_c.so" CACHE
    STRING "Path to ARCORE library"
    FORCE
)
set(ARCORE_INCLUDES "${ARCORE_INCLUDE}" CACHE
    STRING "Path to ARCORE headers"
    FORCE
)
mark_as_advanced(FORCE ARCORE_LIBRARIES)
mark_as_advanced(FORCE ARCORE_INCLUDES)

set_target_properties(ARCORE::ARCORE PROPERTIES
    IMPORTED_LOCATION "${ARCORE_LIBRARIES}"
    INTERFACE_INCLUDE_DIRECTORIES "${ARCORE_INCLUDE}"
)
