// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MESSAGECONTROL_STD_MSGS_H_
#define FLATBUFFERS_GENERATED_MESSAGECONTROL_STD_MSGS_H_

#include "flatbuffers/flatbuffers.h"

namespace std_msgs {

enum class MessageControl : uint8_t {
  ACK = 1,
  MIN = ACK,
  MAX = ACK
};

inline const MessageControl (&EnumValuesMessageControl())[1] {
  static const MessageControl values[] = {
    MessageControl::ACK
  };
  return values;
}

inline const char * const *EnumNamesMessageControl() {
  static const char * const names[2] = {
    "ACK",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageControl(MessageControl e) {
  if (flatbuffers::IsOutRange(e, MessageControl::ACK, MessageControl::ACK)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(MessageControl::ACK);
  return EnumNamesMessageControl()[index];
}

}  // namespace std_msgs

#endif  // FLATBUFFERS_GENERATED_MESSAGECONTROL_STD_MSGS_H_
